Make SpinnerImage more robust
sublime-music/sublime-music pull request #390
Opened 2023-03-16 14:22 UTC by jlxip

I've found some errors on sublime-music's output, regarding artwork files containing the text "Artwork not found" instead of a JPEG. This PR makes it a little bit more robust.

2023-03-16 14:32 UTC, sumnerevans requested changes

2023-03-16 14:32 UTC, sumnerevans commented on sublime_music/ui/common/spinner_image.py
> +                # File contents might be "Artwork not found"
Let's at least log the exception here.

2023-03-16 14:43 UTC, jlxip commented on sublime_music/ui/common/spinner_image.py
> +                # File contents might be "Artwork not found"
Done

2023-03-16 14:47 UTC, sumnerevans requested changes

2023-03-16 14:47 UTC, sumnerevans commented on sublime_music/ui/common/spinner_image.py
> +                      "Probably not an image. \"Artwork not found\"?")
Use `logging`, not `print`, and also include the actual exception

```suggestion
                logging.warn(f"could not load {filename}. Probably not an image. {e}")
```

2023-03-16 15:04 UTC, sumnerevans requested changes

2023-03-16 15:04 UTC, sumnerevans commented on sublime_music/ui/common/spinner_image.py
> +            except:
```suggestion
            except Exception as e:
```

2023-03-16 18:22 UTC, jlxip commented
Squashing. Please wait

2023-03-16 18:25 UTC, jlxip commented
Should be OK now. I also imported `logging`.

2023-03-16 22:17 UTC, sumnerevans approved these changes

2023-04-10 15:48 UTC, sumnerevans commented
Please fix the linter error and then I'm fine with merging this.

2023-04-12 17:16 UTC, merged